// Given a string containing only the characters '(' and ')', generate all possible subsequences of the string. A subsequence is derived by deleting some characters (possibly zero) without changing the order of the remaining characters.



// Return the list of all distinct subsequences in any order.



// Example 1:

// Input: s = "()"

// Output: ["","(",")","()"]

// Explanation: All possible subsequences are generated by including or excluding each character.



// Example 2:

// Input: s = "(()"

// Output: ["","(",")","((","()","()"]

// Explanation: There are 6 distinct subsequences even though there are 8 total subsequences, because "(" and "()" can each be formed in multiple ways.

// Input format :
// A single line containing a string s.

// The string s consists only of '(' and ')'.

// Output format :
// Print a list (array) of all distinct subsequences of the string s.



// Refer to the sample output for the formatting specifications.﻿

// Code constraints :
// 1 <= len(s) <= 20

// Sample test cases :
// Input 1 :
// ()
// Output 1 :
// ["",")","(","()"]
// Input 2 :
// (()
// Output 2 :
// ["",")","(","()","((","(()"]

#include <iostream>
#include<string>
#include<vector>
#include<set>
using namespace std;
// Recursive function to generate all subsequences
void generateSubsequences(string &s, int index, string current, set<string> &result) {
    if (index == s.size()) {
        result.insert(current);  // store distinct subsequences
        return;
    }

    // Include current character
    generateSubsequences(s, index + 1, current + s[index], result);

    // Exclude current character
    generateSubsequences(s, index + 1, current, result);
}

int main() {
    string s;
    cin >> s;

    set<string> result;
    generateSubsequences(s, 0, "", result);

    // Print result in the requested format
    cout << "[";
    bool first = true;
    for (auto &sub : result) {
        if (!first) cout << ",";
        cout << "\"" << sub << "\"";
        first = false;
    }
    cout << "]" << endl;

    return 0;
}